spring:
  application:
    name: 01-Sec_JWT_App-4

  datasource:
    username: root
    password: user@123
    url: jdbc:mysql://localhost:3306/springdb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

