server:
  port: 3333

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: welcome-api
          uri: lb://WELCOME-API
          predicates:
            - Path=/welcome

        - id: greet-api
          uri: lb://GREET-API
          predicates:
            - Path=/greet
